### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Akifumi-Tsukada** [Akifumi-Tsukada/furima-34710#9]
入力内容 | 情報
-- | --
自身のフリマアプリのURL | https://furima-34710.herokuapp.com
Basic認証のIDとパスワード | admin , 1234
出品者用のメールアドレスとパスワード | test1@example , testuser1
購入者用のメールアドレスとパスワード | test2@example , testuser2

**Comment by snkw-works** [comment]
@Akifumi-Tsukada さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **商品詳細ページにて、商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されるよう修正しましょう**
商品説明が正しく表示されていません。
<img width="1440" alt="スクリーンショット_2021-05-23_15_52_20" src="https://user-images.githubusercontent.com/54050089/119251005-ee4ba200-bbde-11eb-9fde-0a6c474345c9.png">

- [ ] **商品購入の際、配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であるよう修正しましょう**
「都道府県」の入力がなくても購入ができてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Akifumi-Tsukada** [comment]
修正が完了しました。ローカル環境では挙動の確認済です。
ご確認お願いします。

https://gyazo.com/09009b5b253ca72fc58cc46bcb28773c
https://gyazo.com/b87c47e3e2d69485bfe0342a9c496198

**Comment by snkw-works** [comment]
@Akifumi-Tsukada さん、お待たせいたしました。ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

【補足】
購入画面で8都道府県のみ選択できるようになっています。必須要件とはなっておりませんが、可能であれば47都道府県が選択できるよう修正しましょう。（修正のご報告は不要です）
<img width="421" alt="スクリーンショット 2021-05-24 12 34 42" src="https://user-images.githubusercontent.com/54050089/119293249-fb26cf00-bc8c-11eb-9785-692d8f847b6c.png">


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/119293134-be5ad800-bc8c-11eb-8a9b-57e91bd14c42.png)
